### ISSUE TITLE
Review of the Release Engineering backlog

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/sig-release#1069]
In the search for something to work on, I've gone through the [Release Engineering backlog](https://github.com/orgs/kubernetes/projects/30#column-5196854). However, I've noticed a couple of issues that:
* haven't been updated for a long time
* are stale or rotten and close to being closed by the bot

Some of those issues are potentially not relevant anymore (as things are changing quite fast nowadays), but some are still relevant.

I've decided to build a list with affected issues along with a proposed action and explanation. I hope this will help to tidy the backlog a bit, as well as, that we don't lose any relevant issue.

## Candidates for closing

**Some of those issues already has `lifecycle/rotten` and will be closed soon**

* [x] Testing bash scripts: PR feedback (https://github.com/kubernetes/release/issues/855)
  * Status: **closed**
  * `lifecycle/rotten` along with `help wanted` (and mentioned as good for associates)
  * Proposed action: close.
  * This is an older issue about testing our bash scripts. As we are switching to Go and `krel`, and with `anago` being deprecated, is it worth investing time into this?
* [x] gcbmgr release frequently fails at "push git objects" (https://github.com/kubernetes/release/issues/933)
  * Status: **closed**
  * `lifecycle/rotten`
  * Proposed action: close.
  * AFAIK, we have got ridden of `gcbmgr`.
* [x] [anago] Potential improvements for logging k/release repo information (https://github.com/kubernetes/release/issues/1028)
  * `lifecycle/rotten` and `help wanted`
  * Proposed action: ~close~ (@justaugustus -- leave open, I left a comment)
  * Status 8/5: Relevant for `krel`. Should we update the issue title/description to mention this?
  * As anago is deprecated and we are going towards Go tools, is this something we want to touch? Although, this is something that still might be useful, so I'm on the fence on this one.

## Candidates for closing or freeze

* [x] RFC -- Investigate concourse for release pipelines (https://github.com/kubernetes/release/issues/848)
  * Status: **closed**
  * `lifecycle/rotten`
  * Proposed action: `lifecycle/frozen` or close.
  * I think that we have got quite experienced GCB over the time, it works well for us, and we are sponsored by Google for infra. While I love experimenting with the new stuff, I think this would require a lot of time-wise investment, so we should eventually leave it aside for now until we don't finish the main tooling-related tasks.
* [x] Consider using RPM spec with debbuild for creating Debian packages (https://github.com/kubernetes/release/issues/996)
  * `lifecycle/rotten`
  * This looks like a nice idea. Although the `debbuild` project doesn't seem to be a popular one, so it might be harder to find someone with the experience or some project that's already using it. That introduces a little bit of a risk.

## Issues that are stale but shouldn't be

* [x] Analyze current release tooling (https://github.com/kubernetes/release/issues/837)
  * Status: **closed**
  * `lifecycle/rotten`
  * I think this is something that might be very useful. We should check in what state this is in and eventually update and expand it.

## Frozen issues that are candidates to be worked on

* [x] Add check to verify-boilerplate (https://github.com/kubernetes/release/issues/777)
  * It's still unclear what's the status of `repo-infra`, but it seems like copying from it is an okay approach. If that's right, I think we should attempt to fix what can be fixed and then create a follow-up issue to use `repo-infra` when it becomes possible.

---

So far, I've just looked at issues with no one assigned (by using the `no:assignee` filter). If this is something that seems useful to you or that you like, I can also take a look at issues with assignees and ping them to check for the status. After that, I can create a similar report as well.

/assign @justaugustus @xmudrii

**Comment by xmudrii** [comment]
I'll try to label the issue, please fix it if I make some mistake.

/sig release
/area release-eng
/kind cleanup

I'd say that priority is important-soon, but I'd leave it on @justaugustus or someone else with more experience.

**Comment by markyjackson-taulia** [comment]
Awesome work @xmudrii I will ping you to help

**Comment by Conan-Kudo** [comment]
From @xmudrii:

> This looks like a nice idea. Although the `debbuild` project doesn't seem to be a popular one, so it might be harder to find someone with the experience or some project that's already using it. That introduces a little bit of a risk.

Depends on how you judge popularity. If you're judging it by contributions on GitHub, it's probably not considered very popular.

However, it is used by a fair number of projects, such as Microsoft's Linux [`procdump`](https://github.com/microsoft/ProcDump-for-Linux), Red Hat's [Spacewalk project](https://github.com/spacewalkproject/spacewalk/tree/master/client/debian), Fedora's [Cobbler project](https://github.com/cobbler), the [KIWI project](https://github.com/OSInside/kiwi), and Datto's [`dattobd` kernel module](https://github.com/datto/dattobd).

There's also a fair number of random packages using it on the openSUSE Build Service since OBS supports building Debian/Ubuntu packages using `debbuild`.

**Comment by xmudrii** [comment]
The last time I've gone through the unassigned issues in the backlog. After the positive feedback, I've decided to go through all issues in the backlog.

Right now, there are 28 issues in the backlog. Just like the last time, I've highlighted some relevant issues and proposed the action. I haven't mentioned some issues that are newly added or work-in-progress.

## Issues in the v1.18 milestone

There are a couple of issues with the v1.18 milestone. Since v1.18 has been released couple of weeks ago, we should move those issues to another milestone.

* [ ] Signing releases with GPG keys (https://github.com/kubernetes/release/issues/914)
  * Status: assigned; pinged and awaiting response
  * Proposed action: move to the v1.19 milestone and eventually reassign due to inactivity
* [ ] Support for Debian Buster (https://github.com/kubernetes/release/issues/728)
  * Status: assigned; pinged and awaiting response
  * Proposed action: move to the v1.19 milestone and eventually reassign due to inactivity
* [x] kubernetes yum repository using remote paths with ../../pool and odd filenames (https://github.com/kubernetes/release/issues/689)
  * Status: unassigned issue with `help wanted`
  * Taken action: moved from v1.18 to the v1.19 milestone
* [ ] Should release-notify script send from GCB? (https://github.com/kubernetes/release/issues/959)
  * Status: Assigned issue with `lifecycle/rotten`
  * Proposed action: eventually reassign due to inactivity
  * Taken action: moved to the v1.19 milestone and removed the `lifecycle/rotten` label
* [x] Build release notes for alpha.0 and beta.0 releases (https://github.com/kubernetes/release/issues/1119)
  * Status: assigned; pinged and received an update
  * Taken action: moved to the v1.19 milestone

## Issues with the `lifecycle/frozen` label

There are couple of issues with the `lifecycle/frozen` label in the backlog. We should reconsider are some issues still frozen.

* [ ] RPMs should be gated with kubeadm and then tagged (https://github.com/kubernetes/release/issues/305)
  * Status: assigned; last activity in December 2019; pinged and awaiting response
* [ ] Kubernetes build has grown bloated. (https://github.com/kubernetes/kubernetes/issues/16753)
  * Status: unassigned; last activity in May 2019
  * Proposed action: ping to check is it still relevant and do we want/can we fix it
* [ ] Use semantic import versioning for published staging repos (https://github.com/kubernetes/kubernetes/issues/72638)
  * Status: unassigned; last activity in January
* [ ] Eliminate the docker load from the production (https://github.com/kubernetes/kubernetes/issues/24123)
  * Status: assigned; last activity in May 2019; pinged and awaiting response
* [ ] remove experimental docker feature enabling (https://github.com/kubernetes/release/issues/628)
  * Status: unassigned; last activity in December 2019
  * Proposed action: ping to check is it still relevant

## Other issues

Issues that we should keep an eye on them.

* [ ] Discuss feature branches/forks (https://github.com/kubernetes/kubernetes/issues/85892)
  * Status: assigned; no activity since February; pinged and awaiting response
  * This issue might be important to be fixed soon
  * Proposed actions: eventually reassign due to inactivity; assign to a milestone
* [ ] Alternatives to GCR hosted images for building/testing k8s (https://github.com/kubernetes/kubernetes/issues/78679)
  * Status: unassigned; no milestone; last activity in February
  * This issues still seems relevant
  * Proposed action: decide do we want to work on it, assign a milestone, and agree how to fix it
* [ ] Kubernetes support for mips64le (https://github.com/kubernetes/kubernetes/issues/87056)
  * Status: unassigned; no milestone; last activity 25 days ago

## Good first issues

* [ ] Evaluate github.com/tallclair/mdtoc as replacement for our implementation (https://github.com/kubernetes/release/issues/1010)
  * Status: assigned; last activity 19 days ago; pinged and awaiting response

## Community-wide issues

The community-wide issues include issues that affect multiple SIGs and may require a lot of discussions. For example, a LTS release is considered a community-wide issue. There are about 6 community-wide issues.

* [ ] plan a short cycle stability release (https://github.com/kubernetes/sig-release/issues/809)
* [ ] [umbrella issue] bash in kubernetes (https://github.com/kubernetes/kubernetes/issues/78702)
* [ ] Test infra code freeze to aid in stability for the kubernetes release (https://github.com/kubernetes/sig-release/issues/907)
* [ ] Permissions to add minikube packages to Kubernetes repos (.deb, .rpm) (https://github.com/kubernetes/release/issues/839)
* [ ] Scalability tests for beta releases (https://github.com/kubernetes/sig-release/issues/908)
* [ ] Increase Kubernetes support window to one year (https://github.com/kubernetes/enhancements/issues/1498)

**Comment by xmudrii** [comment]
I've noticed that the number of issues in the backlog and other columns has got decreased compared to the last week. I've gone through the project activity and collected all issues that got closed by the bot in the last couple of days. I thought this might be useful, so we don't lose potentially relevant issues.

## Backlog issues that got closed recently

### Candidates for reopening

All those issues still seem relevant to me, so I propose to reopen them.

* [ ] Separate binary publishing from latest release marker file update (https://github.com/kubernetes/sig-release/issues/390)
  * priority/important-longterm
* [ ] Document GCS buckets and their usage (https://github.com/kubernetes/release/issues/944)
  * priority/important-longterm
* [ ] automated build trigger and validation of RPMs/Debs (https://github.com/kubernetes/release/issues/631)
  * priority/important-soon
* [ ] Announcement template updates (https://github.com/kubernetes/release/issues/844)
  * priority/important-longterm

### Issues that should remain closed

* [ ] [anago] publishing-bot issue creation is noisy (https://github.com/kubernetes/release/issues/712)
  * Since we're switching away from anago, is it worth spending time on it?
* [ ] [anago] publishing-bot issue does not assign correctly
  * priority/important-longterm
  * Since we're switching away from anago, is it worth spending time on it?

### Unclear status

* [ ] bsdmainutils requirement limits gcbmgr to debian distros (https://github.com/kubernetes/release/issues/684)
  * priority/important-soon
  * It's unclear to me is it still relevant or no

## To do issues that got closed recently

### Candidates for reopening

* [ ] Patch release process should update kubernetes/website Kubernetes versions (https://github.com/kubernetes/sig-release/issues/626)
  * priority/important-longterm
  * As far as I know, this issue is still not fixed and it probably still relevant
* [ ] cherry pick process enhancements (https://github.com/kubernetes/sig-release/issues/611)
  * This still seems like a relevant issue
* [ ] Document current usage of kubernetes version marker files (https://github.com/kubernetes/sig-release/issues/759)
  * This still seems like a relevant issue

### Unclear status

* [ ] bot feedback on PRs for patch release branches (https://github.com/kubernetes/sig-release/issues/680)
  * It seems like some tasks are already resolved, but there still might be some tasks to take care of

## In progress issues that got closed recently

### Unclear status

* [ ] More refined guidance for Release Manager Associates (https://github.com/kubernetes/sig-release/issues/695)
* [ ] Unify release notes tooling (https://github.com/kubernetes/release/issues/954)

**Comment by LappleApple** [comment]
I've updated this list to reflect all items either Closed or Done, and collected the remainder/unresolved items for us to review via a new GitHub issue. There was some slight overlap of issues here and in past retro items so I'll consolidate.
