### ISSUE TITLE
1.19 Action Items Umbrella Issue

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/sig-release#1178]
This is a rolling list of issues, topics and action items that come up through the end of the 1.19 cycle.

**WEEK OF July 20**
Bundle of items pitched by @liggitt on CI / prow policy changes
  - [ ] _to formalize in policy and enforce going forward_: require contact information / list email notifications for all jobs that are not on the informing/blocking dashboards the release team looks at. (**Q:** Should have been formalised, but is it enforced? Somewhat, at the test level, but based on whether a job is blocking or not—but not so much whether it has an email address. We should also give this another sweep -- open up an issue. Owners: @cpanato, @hasheddan)
- [ ] Once CI infrastructure issues are stabilized, follow up to focus on SIG-driven / test-specific fixes
  - [ ] [list of suggestions from @liggitt](https://docs.google.com/document/d/1a2JqY8TFut_bal3T3uYbid2mYJFJY4mqZNn8DHT8I0A/edit)
  - [ ]  open issues with clear owners targeting improving some of our slowest tests ([e.g.](https://github.com/kubernetes/kubernetes/issues/87807#issuecomment-662532855) ) 
  - [ ] open issues with clear owners targeting deduping some of our presubmits and/or moving some to postsubmit/periodic ([e.g.](https://github.com/kubernetes/kubernetes/issues/92937#issuecomment-662178519), see [also](https://github.com/kubernetes/kubernetes/issues/92937#issuecomment-662699230))

****
[CI Signal subproject](https://github.com/kubernetes/sig-release/issues/966)
- [x] Get this topic on the next sig-testing meeting, stripping potentially controversial ideas and go with the goal of formation: @alejandrox1 to do this.
 - Noting this [Very few PRs are merging](https://github.com/kubernetes/kubernetes/issues/92937) issue
- Note via @BenTheElder: "Items around changing what tests run and requirements for running are explicitly in scope for SIG Testing. We've already moved on some of this."
- use the CI Signal handbook to create the vision for the subproject

****
- [x] Need interlock with sig-scalability regarding upgrade to new go versions: releng, sig-scalability AIs | owner: @justaugustus to drop sig-scalability an email to get the conversation restarted.

****
- [ ] Decide how to present/promote Stephen's three hours of new content (videos) related to Go upgrades. There's a code walkthrough list, and can also be on the sig-release playlist. Blog post on the Go update? | Owner: @justaugustus to finish documentation about upgrade before we hype this.

****
- [ ] Decide how to present/promote Veronica's Bazel notes | @Verolop

**Comment by LappleApple** [comment]
Going to close this to reconsider a different tracking/issue approach.
