### ISSUE TITLE
☂️ CI Policies improvements 

### ISSUE THREAD

**Issue by cpanato** [kubernetes/sig-release#1215]
This is an issue that will cover the work that needs to be complete in order to have some CI policies and improvements.
We have a previous [issue](https://github.com/kubernetes/sig-release/issues/1178) to describe, but now we know a little bit more so we are creating this issue and the child issues to cover some actions we will do in the following weeks

- [ ] For existing Job: add the contact information in case of job issue it will send out a notification - [GH Issue](https://github.com/kubernetes/sig-release/issues/1216)
- [ ] Describe and write down the CI policy. Possible [place](https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md) for this information - [GH Issue](https://github.com/kubernetes/sig-release/issues/1217)
- [ ] Add a presbumit job to validate if updated jobs/new jobs follow the policy and have the necessary information. - [GH Issue](https://github.com/kubernetes/sig-release/issues/1218)

/area release-eng
/area ci
/kind documentation
/priority important-soon
/milestone v1.20

/cc @hasheddan @puerco @alejandrox1

**Comment by cpanato** [comment]
will close because it is a duplicate of https://github.com/kubernetes/test-infra/issues/18551

/close
