### ISSUE TITLE
[Umbrella] Refactor the Release Engineering Handbooks

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/sig-release#1324]
This issue is an umbrella issue to track the progress of refactoring the release engineering handbooks.

- [ ] Split the [Branch Management handbook](https://github.com/kubernetes/sig-release/blob/667bf705e2fe9350fb12f3ba09bb5380f6b01a63/release-engineering/role-handbooks/branch-manager.md) into multiple handbooks
  - [ ] [Release Management handbook](https://github.com/kubernetes/sig-release/blob/667bf705e2fe9350fb12f3ba09bb5380f6b01a63/release-engineering/role-handbooks/branch-manager.md#releases-management)
    - [ ] Improve the handbook formatting and wording
  - [ ] [Branch Management handbook](https://github.com/kubernetes/sig-release/blob/667bf705e2fe9350fb12f3ba09bb5380f6b01a63/release-engineering/role-handbooks/branch-manager.md#branch-management)
    - [ ] Ensure the handbook is up to date
    - [ ] Improve the handbook formatting and wording
- [ ] Merge the [Patch Release Team handbook](https://github.com/kubernetes/sig-release/blob/667bf705e2fe9350fb12f3ba09bb5380f6b01a63/release-engineering/role-handbooks/patch-release-team.md) with the other handbooks
- [ ] Consider moving the role-handbooks in the filesystem tree above other documents
- [ ] Document the needed IAM privileges for running tasks mentioned in the handbooks

/kind documentation
/area release-eng
/priority important-soon
/milestone v1.20
/assign

**Comment by xmudrii** [comment]
cc: @kubernetes/release-engineering 
If you have any feedback regarding our handbooks, please feel free to leave it here.

**Comment by saschagrunert** [comment]
Do we still have an onboarding document after those changes? Generally spoken, those two sections:

- https://github.com/kubernetes/sig-release/blob/667bf705e2fe9350fb12f3ba09bb5380f6b01a63/release-engineering/role-handbooks/branch-manager.md#overview
 - https://github.com/kubernetes/sig-release/blob/667bf705e2fe9350fb12f3ba09bb5380f6b01a63/release-engineering/role-handbooks/branch-manager.md#prerequisites

**Comment by xmudrii** [comment]
@saschagrunert I propose that we have some general/onboarding handbook that would be common for all other handbooks. It would include most of the things from those two links, and eventually some other useful references as well.

**Comment by LappleApple** [comment]
@pmmalinov01 interested in helping with this--what are some break-out tasks he could get started with?

**Comment by puerco** [comment]
Assigning Carlos to help with the handbook refactor
/assign @cpanato

**Comment by xmudrii** [comment]
I'm not working on this at the moment.
/unassign
