### ISSUE TITLE
[Epic] Artifact Management

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1372]
#### What would you like to be added:

We need a cohesive story around artifact management.

Broadly, this will cover:
- File artifacts
- Container images
- deb/rpm packages

There are several issues which describe various aspects of developing a process, as well as user feature requests, so to start, we should do some issue collection.

- [x] Create an "Epics" column in the SIG Release project board and add this epic to it
- [x] Create a project board for artifact management: https://github.com/orgs/kubernetes/projects/48
- [x] Add the `area/artifacts` label to repos which may contain artifact issues/PRs: https://github.com/kubernetes/test-infra/pull/20111
- [x] Scrape the respective repos for artifact issues/PRs and tag w/ `area/artifacts`
- [x] Add aforementioned issues/PRs to the Artifact Management project board
- [ ] KEP cleanup:
  - [ ] Image Promotion: https://github.com/kubernetes/enhancements/issues/1734
  - [ ] Artifact Management: https://github.com/kubernetes/enhancements/issues/1732
  - [ ] Publishing Packages: https://github.com/kubernetes/enhancements/issues/1731
- [ ] Further populate this list and cross link all artifact issues/PRs to the epic

/assign
/milestone v1.21
cc: @kubernetes/sig-release-leads @kubernetes/release-engineering 

---

Tasks from https://github.com/kubernetes/k8s.io/issues/170:

- [ ] Design Document describing how all this will work.
- [ ] GCR Repository for official published images
- [ ] GCR Repository for projects to use (https://github.com/kubernetes/k8s.io/issues/158)
- [ ] GCS Bucket for projects to use (https://github.com/kubernetes/k8s.io/issues/153)
- [ ] Process for image promotion (https://github.com/kubernetes/k8s.io/issues/157)
- [ ] ECR Repository mirror for Amazon
- [ ] ACR Repository mirror for Azure
- [ ] HTTP Redirector for image and artifact renaming.

and @spiffxp's notes:

> /remove-help
> I don't think this is appropriately scoped for help wanted
> 
> /priority important-longterm
> Very important for the longterm health of this project. We've migrated image hosting (k8s.gcr.io), but we haven't migrated binary artifact hosting (dl.k8s.io). So we're not all the way done and already hosting/serving artifacts is a very non-trivial amount of our spend We will need to start the conversation back up on mirroring.

> Issue covers too much, should break into:
> 
>     * k8s.gcr.io mirroring
>     * binary artifact promotion
>     * artifact mirroring
>
> Can close once those are created

**Comment by justaugustus** [comment]
Tasks from https://github.com/kubernetes/k8s.io/issues/170:

- [ ] Design Document describing how all this will work.
- [ ] GCR Repository for official published images
- [ ] GCR Repository for projects to use (https://github.com/kubernetes/k8s.io/issues/158)
- [ ] GCS Bucket for projects to use (https://github.com/kubernetes/k8s.io/issues/153)
- [ ] Process for image promotion (https://github.com/kubernetes/k8s.io/issues/157)
- [ ] ECR Repository mirror for Amazon
- [ ] ACR Repository mirror for Azure
- [ ] HTTP Redirector for image and artifact renaming.

and @spiffxp's notes:

> /remove-help
> I don't think this is appropriately scoped for help wanted
> 
> /priority important-longterm
> Very important for the longterm health of this project. We've migrated image hosting (k8s.gcr.io), but we haven't migrated binary artifact hosting (dl.k8s.io). So we're not all the way done and already hosting/serving artifacts is a very non-trivial amount of our spend We will need to start the conversation back up on mirroring.

> Issue covers too much, should break into:
> 
>     * k8s.gcr.io mirroring
>     * binary artifact promotion
>     * artifact mirroring
>
> Can close once those are created

**Comment by justaugustus** [comment]
More ideas from the Twitterverse: https://twitter.com/pythomit/status/1353794885099245568?s=19

cc: @tpepper

**Comment by ameukam** [comment]
/assign @hh 
Because of : 
> HTTP Redirector for image and artifact renaming.
