### ISSUE TITLE
Use GH project for K8s 1.26 enhancement tracking

### ISSUE THREAD

**Issue by marosset** [kubernetes/sig-release#2009]
Creating an issue to track discussions / work needed to use GH projects for enhancement tracking for K8s v1.26 release instead of Google sheets.

This has been discussed at both v1.25 release retrospectives [notes](https://docs.google.com/document/d/1XvBrK3XYZ3mLVVSOchdgFRPmbW-1V9BdZhaDAesANFs)

Open issues
- Automation
  - [ ] Is this even a blocker? Adding items to google sheets was pretty manual.
  - [x] Check in script to sync issues to project board - https://github.com/kubernetes/sig-release/pull/1968
  - [x] Periodically sync issues to board
    - Can do something similar https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/.github/workflows/sync-sig-windows-projects-k8s.yml or use PROW
- Process
  - [x] Decide where project should live (https://github.com/kubernetes/enhancements/projects or https://github.com/orgs/kubernetes/projects
  - [x] Draft guidance to SIG leads
  - [ ] Update role-handbook regarding creation of new project board for each release
  - [x] Can we trust milestone-maintainers to not abuse tags or do we need to lock some tags down to release team?
    - [x] New label `lead-opted-in` created and usage has been restricted to current SIG leads 
- Misc
  - [ ] Sheets provided nice stats around things like enhancements per sig, number of KEPs in each stage etc, are we OK losing this? It looks like this **is** possible.
  - [x] Create mailing group in case anyone has questions/concerns.
  
  This is still a **WIP** but we need to start the discussions **NOW** for this to happen in v1.26
  
  /cc @rhockenbury @gracenng @justaugustus @cici37 @Priyankasaggu11929 @reylejano

**Comment by palnabarun** [comment]
Is 1.26 a right target for this? The tracking has to begin starting next Monday.

**Comment by leonardpahlke** [comment]
I would stick for now with the spreadsheet and make sure we get the project board for 1.27 up and running. Maybe we can use both simultaneously? @gracenng @Priyankasaggu11929 WDYT?

**Comment by marosset** [comment]
In the release retro yesterday, there was a desire to not maintain state in sheets and GH projects simultaneously.

**Comment by gracenng** [comment]
For now, periodic and manual trigger is okay imo.

What @marosset said, we (including SIG-Release leads) decided in retro that we will just bite the bullet and do only project beta which means we'll need to:

- [ ] Decide which tag we are collecting on. Ideally this is a new tag because `milestone-maintainer` has been consistently misused in past releases - **how to we make a new one?**
- [ ] Blog post for the changes - what this means, how it works, motivations. I'll own this and add y'all as collabs. Will get this done by Sunday hopefully.
- [ ] Since @leonardpahlke already sent out sneak peek, we will need to email k-dev again with said blog post since this is a major change.

**Comment by marosset** [comment]
@gracenng I was able to create a new label at https://github.com/kubernetes/enhancements/labels (I think because I got elevated access to for being on the v1.25 enhancements team) 
I created `release-team-approved`. I'm not sure how to restrict who can add this label to issues tho.

**Comment by palnabarun** [comment]
Copying my thoughts from Slack (https://kubernetes.slack.com/archives/C02BY55KV7E/p1662060771020379?thread_ts=1662054929.812849&cid=C02BY55KV7E):

TODOs in my POV:
1. Figure out how the restricted labels config works and set tracked/* to be only used by enhancements team members in k/enhancements.
2. Prepare a process doc for the community.
3. Prepare a process doc for the enhancements team.
4. Draft an email detailing the process change and link to doc in #2.

#2 is very important to be sent before/when the enhancements collection email is sent.

**Comment by rhockenbury** [comment]
Hello everyone. Providing an update here to capture what's left to be done.  I'm separating things out into two categories - High Priority (we should get it done by v1.27) and Low Priority (can be left to future release cycles). 

## High Priority 

#### Communication
- [ ] Reminders to SIG leads about opt-in process changes in early v1.27 and probably v1.28

#### Script / Sync Job Changes
- [ ] Debug issue with Github token and get job fully working with automation
- [ ] Script documentation including env vars, scopes for token, cli tools (jq, gh), and how to run manually
- [ ] Process for pausing sync job after enhancements freeze OR restricting use of `lead-opted-in` label (See
https://github.com/kubernetes/test-infra/pull/27699)

#### Role Handbook
- [ ] Add docs around sync job monitoring / [testgrid dashboard ](https://testgrid.k8s.io/sig-release-release-team-periodics#periodic-sync-enhancements-github-project-beta-1-26) / debugging job
- [ ] Add docs for setting up Github teams for use with Project board
- [ ] Add docs for setting up the project board (permissions, fields, field values, charts, etc)
- [ ] Add docs for restrictions on `tracked/*` labels and `lead-opted-in` label
- [ ] Review and update docs in handbook Process section - [Week 0](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#pre-enhancements-freeze-week-0)
- [ ] Review and update docs in handbook Process section - [Week 1](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#pre-enhancements-freeze-week-1)
- [ ] Review and update docs in handbook Process section - [Week 1-2](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#collection-monitoring-and-triage-week-1-2)
- [ ] Review and update docs in handbook Process section - [Week 3](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#enhancements-freeze-week-3)
- [ ] Review and update docs in handbook Process section - [Week 4-10](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#post-enhancements-freeze-week-410)
- [ ] Review and update docs in handbook Process section - [Week 10+](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#code-freeze-week-10)
- [ ] Review and update docs in handbook ["Working with the enhancements tracking sheet"](
https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#working-with-the-enhancement-tracking-sheet)

## Low Priority 

#### Script / Sync Job Changes
- [ ] Add ability to filter out PRs (rather than enhancements) that have `lead-opted-in` label and/or log a warning when this occurs
- [ ] Additional stdout logging in sync script to log basic metrics for each run (how many enhancements were added, by which sigs, etc)
- [ ] Add ability for sync script to populate "enhancement status" and "owning sig" columns on project board by looking at labels, first comment on issue and/or parsing the KEP.yaml (assuming post alpha, and it has a merged KEP.yaml)

#### Project Board
- [ ] Push forward on features for more granular permissions for project board (See https://github.com/community/community/discussions/7478)
- [ ] Push forward on features for cloning/ copying and configuring project board (See https://github.com/community/community/discussions/8357,
https://github.com/community/community/discussions/7908, and
https://github.com/community/community/discussions/21089)
- [ ] Review metrics / charting capabilities and automate metrics collection around k8s release (See https://github.com/kubernetes/sig-release/issues/1527#issuecomment-1239069005)

**Comment by leonardpahlke** [comment]
/close 

I created a new issue to follow this one up: https://github.com/kubernetes/sig-release/issues/2109
