### ISSUE TITLE
[Tracking] Use the enhancements project board for future release cycles

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/sig-release#2109]
The change in the release team's tracking of enhancements from spreadsheets to GitHub project boards in version 1.26 was very well received, and so we would like to continue using the new tracking of enhancements in the upcoming release cycles. 

We discussed how to proceed in the sig-release meeting (Dec 6) - it was discussed whether the current board can be reused in each cycle or a new board should be created. It was decided to create a new project board for each release cycle (see sig-release meeting notes). For now, the GitHub project board should follow the form of the current ([1.26](https://github.com/orgs/kubernetes/projects/98)) Enhancements GitHub Project board, but should evolve over time. Project boards from past release cycles will be used as an archive for tracking releases.

**Tasks for using the Enhancements GitHub Project Board for 1.27 and beyond**:
- [x] 1. Create and configure an empty enhancements tracking GitHub project board for the release cycle 1.27 (see [1.26](https://github.com/orgs/kubernetes/projects/98))
     - This should be done soon, so the enhancements team can start collecting KEPs
- [x] 2. Discover current state of the automation tooling and use it for 1.27 (& add documentation to the handbook about it)
     - This should be done soon, so the enhancements team can rely on the automation tooling to update the project board, we partially used prow and GitHub actions during the release; prow is currently broken AFAIK; @rhockenbury, @Priyankasaggu11929 
- [x] 3. Document how to setup the enhancements tracking project board each cycle in the [enhancements handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/enhancements) (document 1. & 2.)
- [x] 4. Update general documentation "how to use the project board", and remove the section [how to work with the tracking sheet](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/enhancements#working-with-the-enhancement-tracking-sheet)
- [x] 5. Coordinate with release-docs and release-comms on their views (docs view tab, comms view tab) of the GitHub project board and coordinate on updating handbooks (1.26 Team Lead @fsmunoz @krol3)

/priority important-soon
/milestone v1.27
/assign @salaxander @marosset (1.27 Release Lead, 1.27 Enhancements Lead)
cc EAs, @JamesLaverack  @palnabarun
cc @kubernetes/sig-release-leads

**Comment by marosset** [comment]
#1 is done - https://bit.ly/k8s127-enhancements

**Comment by helayoty** [comment]
We need to duplicate this issue for Bug Triage Board as well. The scripts are merged and ready to be used.

**Comment by marosset** [comment]
Items 1-4 are done.
I believe item 5 is also done.

I think we can close this issue - WDYT @leonardpahlke?
