### ISSUE TITLE
[Tracking] Use the Bug-Triage project board for future release cycles

### ISSUE THREAD

**Issue by helayoty** [kubernetes/sig-release#2209]
The change in the release team's tracking of Bug-Triage from spreadsheets to GitHub project boards in version 1.26 was very well received, and so we would like to continue using the new tracking of bug-triage in the upcoming release cycles.

Tasks for using the Bug-Triage GitHub Project Board for [1.27](https://github.com/orgs/kubernetes/projects/80) and beyond:

- [x]  1. Document how to update the bug-triage tracking project board each cycle in the [bug-triage handbook] (https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/bug-triage) https://github.com/kubernetes/sig-release/pull/2275
- [x] 2. Document how to add/remove bug-triage shadow members to the project board. 
- [x] 3. Update general documentation "how to use the project board", and remove the section [setting-up-the-bug-triage-spreadsheet](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/bug-triage#setting-up-the-bug-triage-spreadsheet)
- [x] 4. Start a conversation on the possibility of merging the `bug-triage` team with `ci-signals` as one team. 

/priority important-soon
/milestone v1.28
cc @gracenng , @leonardpahlke

**Comment by jrsapi** [comment]
@helayoty regarding task number 4. Did this get discussed at the 1.27 mid-cycle retrospective? It would be interesting to hear from both release leads on the possibility of merging.

**Comment by helayoty** [comment]
> @helayoty regarding task number 4. Did this get discussed at the 1.27 mid-cycle retrospective? It would be interesting to hear from both release leads on the possibility of merging.

@jrsapi We had this discussion in the 1.26 repotspictive ([here](https://docs.google.com/document/d/11Oa-L76z8Y1wYufdm1wEV87NUJm1nzQ4b12k6UQY3t8/edit#)). We had an action item to observe the bug-triage during 1.27 and to consider collapsing them by 1.28.

**Comment by leonardpahlke** [comment]
We will not make it for v1.28 but could push it to v1.29.

**Comment by leonardpahlke** [comment]
cc @furkatgofurov7 & @mehabhalodiya

**Comment by furkatgofurov7** [comment]
cross posting from slack conversation: I don't foresee any issues with merging it, but it would be great to have it documented first in the PR so both leads (Bug Triage/CI signal) know in advance what will be changing practically and if there are any complications with it. 

> We will not make it for v1.28 but could push it to v1.29.

 I also think that we probably can make it possible for the next 1.29 release cycle

**Comment by mehabhalodiya** [comment]
> We will not make it for v1.28 but could push it to v1.29.

> I also think that we probably can make it possible for the next 1.29 release cycle

Agree!
