### ISSUE TITLE
[Tracking Issue] GitHub Issue Checklists for Role Lead Progress during a Release Cycle

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes/sig-release#2341]
This GitHub issue is to track creating task checklists for the Release Team's sub-team Role Leads (and their shadows), in order to help them manage their tasks and responsibilities efficiently during a release cycle. 

The purpose of these checklists is to break down all the responsibilities of a Role Lead throughout the 14 weeks of a release cycle into individual tasks. This way, we ensure transparency, avoid any oversights, provide timely help/support and make sure everyone stays informed and aligned.

These checklists will resemble what we currently use, to track the Release Team Lead's progress during a release cycle -  [[1.29] Release Team Lead Cycle Progress](https://github.com/kubernetes/sig-release/issues/2313).

### Definition of Done:

create checklist templates for the following roles:

- [ ] `Comms`  – @krol3 / TBD shadow, @mickeyboxell / @ramrodo )
- [ ] `Docs`  – (@katcosgrove / TBD shadow, @mickeyboxell)
- [ ] `Enhancements` – (@npolshakova / TBD shadow, @Priyankasaggu11929)
- [ ] `Release Notes` – (@fsmunoz / TBD shadow,  @ramrodo)
- [ ] `Release Signal` – (@Vyom-Yadav / TBD shadow, @mehabhalodiya / @neoaggelos)

cc: @kubernetes/release-team-leads, @kubernetes/sig-release-leads

**Comment by drewhagen** [comment]
cc: Release Lead Shadows @jenshu @dipesh-rawat @rytswd @Rajalakshmi-Girish
Since we talked about this idea during release 1.35! Food for thought now or for future cycles.
