### ISSUE TITLE
[Umbrella] Update release team handbooks

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#924]
- [x] Update Enhancements handbook https://github.com/kubernetes/sig-release/issues/918
- [x] Update CI signal team handbook https://github.com/kubernetes/sig-release/issues/919
- [x] Update Bug Triage handbook #920
- [x] Update Docs handbook #834 
- [x] Update Release Notes handbook #922
- [x] Update Communications handbook #923

/milestone v1.18
/priority important-soon
/kind documentation cleanup

**Comment by justaugustus** [comment]
Thanks for getting these opened, @alejandrox1!

**Comment by alejandrox1** [comment]
All the listed handbook updates have been merged
/close

**Comment by alejandrox1** [comment]
/reopen
missed https://github.com/kubernetes/sig-release/issues/834

**Comment by justaugustus** [comment]
/remove-lifecycle rotten
/unassign

Leaving Jorge to finish this up.
/assign @alejandrox1

**Comment by LappleApple** [comment]
I think this can be closed now as @savitharaghunathan closed #834 yesterday
